// <auto-generated />
using System;
using JffEhr.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JffEhr.Api.Migrations
{
    [DbContext(typeof(JffEhrDbContext))]
    [Migration("20260702195506_AddSecurityLayer")]
    partial class AddSecurityLayer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JffEhr.Api.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("audit_id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("action");

                    b.Property<string>("AfterState")
                        .HasColumnType("jsonb")
                        .HasColumnName("after_state");

                    b.Property<string>("BeforeState")
                        .HasColumnType("jsonb")
                        .HasColumnName("before_state");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityTable")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("entity_table");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_address");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("AuditId")
                        .HasName("pk_audit_logs");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_audit_logs_user_id");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("JffEhr.Api.Entities.Camp", b =>
                {
                    b.Property<Guid>("CampId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("camp_id");

                    b.Property<int>("CampNumber")
                        .HasColumnType("integer")
                        .HasColumnName("camp_number");

                    b.Property<string>("CampType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("camp_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("province");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("venue");

                    b.HasKey("CampId")
                        .HasName("pk_camps");

                    b.HasIndex("CampNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_camps_camp_number");

                    b.ToTable("camps", (string)null);
                });

            modelBuilder.Entity("JffEhr.Api.Entities.CampRegistration", b =>
                {
                    b.Property<Guid>("RegistrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("registration_id");

                    b.Property<string>("Cabin")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cabin");

                    b.Property<Guid>("CampId")
                        .HasColumnType("uuid")
                        .HasColumnName("camp_id");

                    b.Property<Guid>("CamperId")
                        .HasColumnType("uuid")
                        .HasColumnName("camper_id");

                    b.Property<string>("GroupName")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("group_name");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("RegistrationId")
                        .HasName("pk_camp_registrations");

                    b.HasIndex("CampId")
                        .HasDatabaseName("ix_camp_registrations_camp_id");

                    b.HasIndex("CamperId")
                        .HasDatabaseName("ix_camp_registrations_camper_id");

                    b.ToTable("camp_registrations", (string)null);
                });

            modelBuilder.Entity("JffEhr.Api.Entities.Camper", b =>
                {
                    b.Property<Guid>("CamperId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("camper_id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("CellNumber")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cell_number");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Diagnosis")
                        .HasColumnType("text")
                        .HasColumnName("diagnosis");

                    b.Property<DateOnly>("Dob")
                        .HasColumnType("date")
                        .HasColumnName("dob");

                    b.Property<Guid?>("FamilyGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("family_group_id");

                    b.Property<string>("FileNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("file_number");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("first_name");

                    b.Property<string>("Language")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("language");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("photo_url");

                    b.Property<string>("Race")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("race");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("sex");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("surname");

                    b.Property<string>("TShirtSize")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("t_shirt_size");

                    b.Property<string>("TreatingClinic")
                        .HasColumnType("text")
                        .HasColumnName("treating_clinic");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("CamperId")
                        .HasName("pk_campers");

                    b.HasIndex("FileNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_campers_file_number");

                    b.ToTable("campers", (string)null);
                });

            modelBuilder.Entity("JffEhr.Api.Entities.CamperAssessment", b =>
                {
                    b.Property<Guid>("AssessmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("assessment_id");

                    b.Property<string>("AdditionalInfo")
                        .HasColumnType("text")
                        .HasColumnName("additional_info");

                    b.Property<string>("AdherenceBarriers")
                        .HasColumnType("text")
                        .HasColumnName("adherence_barriers");

                    b.Property<string>("AdlNeeds")
                        .HasColumnType("jsonb")
                        .HasColumnName("adl_needs");

                    b.Property<string>("Allergies")
                        .HasColumnType("text")
                        .HasColumnName("allergies");

                    b.Property<DateTimeOffset>("AssessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assessed_at");

                    b.Property<Guid>("AssessedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("assessed_by");

                    b.Property<string>("CurrentMedications")
                        .HasColumnType("text")
                        .HasColumnName("current_medications");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("DietaryRequirements")
                        .HasColumnType("text")
                        .HasColumnName("dietary_requirements");

                    b.Property<string>("Eyesight")
                        .HasColumnType("text")
                        .HasColumnName("eyesight");

                    b.Property<string>("Hearing")
                        .HasColumnType("text")
                        .HasColumnName("hearing");

                    b.Property<bool?>("HepatitisB")
                        .HasColumnType("boolean")
                        .HasColumnName("hepatitis_b");

                    b.Property<bool>("MedicationHandedIn")
                        .HasColumnType("boolean")
                        .HasColumnName("medication_handed_in");

                    b.Property<string>("MobilityAids")
                        .HasColumnType("text")
                        .HasColumnName("mobility_aids");

                    b.Property<string>("PhysicalCondition")
                        .HasColumnType("text")
                        .HasColumnName("physical_condition");

                    b.Property<string>("Prosthesis")
                        .HasColumnType("text")
                        .HasColumnName("prosthesis");

                    b.Property<Guid>("RegistrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("registration_id");

                    b.Property<string>("Religion")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("religion");

                    b.Property<string>("SymptomFlags")
                        .HasColumnType("jsonb")
                        .HasColumnName("symptom_flags");

                    b.Property<string>("TbStatus")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tb_status");

                    b.Property<string>("ViralLoad")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("viral_load");

                    b.Property<DateOnly?>("VlTestDate")
                        .HasColumnType("date")
                        .HasColumnName("vl_test_date");

                    b.HasKey("AssessmentId")
                        .HasName("pk_camper_assessments");

                    b.HasIndex("AssessedBy")
                        .HasDatabaseName("ix_camper_assessments_assessed_by");

                    b.HasIndex("DeletedBy")
                        .HasDatabaseName("ix_camper_assessments_deleted_by");

                    b.HasIndex("RegistrationId")
                        .IsUnique()
                        .HasDatabaseName("ix_camper_assessments_registration_id");

                    b.ToTable("camper_assessments", null, t =>
                        {
                            t.HasCheckConstraint("CK_CamperAssessment_DeletedAtDeletedBy", "(deleted_at IS NULL) = (deleted_by IS NULL)");
                        });
                });

            modelBuilder.Entity("JffEhr.Api.Entities.Caregiver", b =>
                {
                    b.Property<Guid>("CaregiverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("caregiver_id");

                    b.Property<Guid>("CamperId")
                        .HasColumnType("uuid")
                        .HasColumnName("camper_id");

                    b.Property<string>("CellNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cell_no");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("relationship");

                    b.Property<string>("WorkNo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("work_no");

                    b.HasKey("CaregiverId")
                        .HasName("pk_caregivers");

                    b.HasIndex("CamperId")
                        .HasDatabaseName("ix_caregivers_camper_id");

                    b.ToTable("caregivers", (string)null);
                });

            modelBuilder.Entity("JffEhr.Api.Entities.ConsentRecord", b =>
                {
                    b.Property<Guid>("ConsentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("consent_id");

                    b.Property<string>("ConsentType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("consent_type");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("DocumentUrl")
                        .HasColumnType("text")
                        .HasColumnName("document_url");

                    b.Property<bool>("PopiaAcknowledged")
                        .HasColumnType("boolean")
                        .HasColumnName("popia_acknowledged");

                    b.Property<Guid>("RegistrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("registration_id");

                    b.Property<DateTimeOffset>("SignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("signed_at");

                    b.Property<string>("SignedBy")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("signed_by");

                    b.Property<string>("SignedLocation")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("signed_location");

                    b.Property<string>("WitnessName")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("witness_name");

                    b.HasKey("ConsentId")
                        .HasName("pk_consent_records");

                    b.HasIndex("DeletedBy")
                        .HasDatabaseName("ix_consent_records_deleted_by");

                    b.HasIndex("RegistrationId")
                        .HasDatabaseName("ix_consent_records_registration_id");

                    b.ToTable("consent_records", null, t =>
                        {
                            t.HasCheckConstraint("CK_ConsentRecord_DeletedAtDeletedBy", "(deleted_at IS NULL) = (deleted_by IS NULL)");
                        });
                });

            modelBuilder.Entity("JffEhr.Api.Entities.CrewMedicalCheckin", b =>
                {
                    b.Property<Guid>("CheckinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("checkin_id");

                    b.Property<string>("Allergies")
                        .HasColumnType("text")
                        .HasColumnName("allergies");

                    b.Property<Guid>("CampId")
                        .HasColumnType("uuid")
                        .HasColumnName("camp_id");

                    b.Property<DateTimeOffset>("CheckedInAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("checked_in_at");

                    b.Property<Guid>("CheckedInBy")
                        .HasColumnType("uuid")
                        .HasColumnName("checked_in_by");

                    b.Property<Guid>("CrewId")
                        .HasColumnType("uuid")
                        .HasColumnName("crew_id");

                    b.Property<string>("CurrentMedications")
                        .HasColumnType("text")
                        .HasColumnName("current_medications");

                    b.Property<string>("Eyesight")
                        .HasColumnType("text")
                        .HasColumnName("eyesight");

                    b.Property<bool>("HasBroviacPort")
                        .HasColumnType("boolean")
                        .HasColumnName("has_broviac_port");

                    b.Property<string>("Hearing")
                        .HasColumnType("text")
                        .HasColumnName("hearing");

                    b.Property<bool>("MedicalReleaseSigned")
                        .HasColumnType("boolean")
                        .HasColumnName("medical_release_signed");

                    b.Property<string>("MobilityAids")
                        .HasColumnType("text")
                        .HasColumnName("mobility_aids");

                    b.HasKey("CheckinId")
                        .HasName("pk_crew_medical_checkins");

                    b.HasIndex("CampId")
                        .HasDatabaseName("ix_crew_medical_checkins_camp_id");

                    b.HasIndex("CheckedInBy")
                        .HasDatabaseName("ix_crew_medical_checkins_checked_in_by");

                    b.HasIndex("CrewId")
                        .HasDatabaseName("ix_crew_medical_checkins_crew_id");

                    b.ToTable("crew_medical_checkins", (string)null);
                });

            modelBuilder.Entity("JffEhr.Api.Entities.CrewMember", b =>
                {
                    b.Property<Guid>("CrewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("crew_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("Dob")
                        .HasColumnType("date")
                        .HasColumnName("dob");

                    b.Property<string>("IdNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("id_number");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("photo_url");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("role");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("surname");

                    b.HasKey("CrewId")
                        .HasName("pk_crew_members");

                    b.HasIndex("IdNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_crew_members_id_number");

                    b.ToTable("crew_members", (string)null);
                });

            modelBuilder.Entity("JffEhr.Api.Entities.EmergencyContact", b =>
                {
                    b.Property<Guid>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("contact_id");

                    b.Property<Guid>("CamperId")
                        .HasColumnType("uuid")
                        .HasColumnName("camper_id");

                    b.Property<string>("CellNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cell_no");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("relationship");

                    b.Property<string>("WorkNo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("work_no");

                    b.HasKey("ContactId")
                        .HasName("pk_emergency_contacts");

                    b.HasIndex("CamperId")
                        .HasDatabaseName("ix_emergency_contacts_camper_id");

                    b.ToTable("emergency_contacts", (string)null);
                });

            modelBuilder.Entity("JffEhr.Api.Entities.MedicationDose", b =>
                {
                    b.Property<Guid>("DoseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("dose_id");

                    b.Property<DateTimeOffset?>("AdministeredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("administered_at");

                    b.Property<Guid?>("AdministeredBy")
                        .HasColumnType("uuid")
                        .HasColumnName("administered_by");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid>("PrescriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("prescription_id");

                    b.Property<DateTimeOffset>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("DoseId")
                        .HasName("pk_medication_doses");

                    b.HasIndex("AdministeredBy")
                        .HasDatabaseName("ix_medication_doses_administered_by");

                    b.HasIndex("DeletedBy")
                        .HasDatabaseName("ix_medication_doses_deleted_by");

                    b.HasIndex("PrescriptionId")
                        .HasDatabaseName("ix_medication_doses_prescription_id");

                    b.ToTable("medication_doses", null, t =>
                        {
                            t.HasCheckConstraint("CK_MedicationDose_DeletedAtDeletedBy", "(deleted_at IS NULL) = (deleted_by IS NULL)");
                        });
                });

            modelBuilder.Entity("JffEhr.Api.Entities.MedicationEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("ContributingFactors")
                        .HasColumnType("jsonb")
                        .HasColumnName("contributing_factors");

                    b.Property<string>("CorrectiveAction")
                        .HasColumnType("text")
                        .HasColumnName("corrective_action");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("DiscoveryAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("discovery_at");

                    b.Property<string>("DoctorNotified")
                        .HasColumnType("text")
                        .HasColumnName("doctor_notified");

                    b.Property<DateTimeOffset>("EventAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_at");

                    b.Property<string>("EventTypes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("event_types");

                    b.Property<string>("ImmediateAction")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("immediate_action");

                    b.Property<Guid>("RegistrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("registration_id");

                    b.Property<Guid>("ReporterId")
                        .HasColumnType("uuid")
                        .HasColumnName("reporter_id");

                    b.Property<Guid?>("ReviewerId")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewer_id");

                    b.Property<string>("TreatmentOrdered")
                        .HasColumnType("text")
                        .HasColumnName("treatment_ordered");

                    b.HasKey("EventId")
                        .HasName("pk_medication_events");

                    b.HasIndex("DeletedBy")
                        .HasDatabaseName("ix_medication_events_deleted_by");

                    b.HasIndex("RegistrationId")
                        .HasDatabaseName("ix_medication_events_registration_id");

                    b.HasIndex("ReporterId")
                        .HasDatabaseName("ix_medication_events_reporter_id");

                    b.HasIndex("ReviewerId")
                        .HasDatabaseName("ix_medication_events_reviewer_id");

                    b.ToTable("medication_events", null, t =>
                        {
                            t.HasCheckConstraint("CK_MedicationEvent_DeletedAtDeletedBy", "(deleted_at IS NULL) = (deleted_by IS NULL)");
                        });
                });

            modelBuilder.Entity("JffEhr.Api.Entities.MedshackTreatment", b =>
                {
                    b.Property<Guid>("TreatmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("treatment_id");

                    b.Property<Guid>("AdministeredBy")
                        .HasColumnType("uuid")
                        .HasColumnName("administered_by");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Outcome")
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.Property<int>("SequenceNo")
                        .HasColumnType("integer")
                        .HasColumnName("sequence_no");

                    b.Property<string>("TreatmentDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("treatment_description");

                    b.Property<DateTimeOffset>("TreatmentTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("treatment_time");

                    b.Property<Guid>("VisitId")
                        .HasColumnType("uuid")
                        .HasColumnName("visit_id");

                    b.HasKey("TreatmentId")
                        .HasName("pk_medshack_treatments");

                    b.HasIndex("AdministeredBy")
                        .HasDatabaseName("ix_medshack_treatments_administered_by");

                    b.HasIndex("DeletedBy")
                        .HasDatabaseName("ix_medshack_treatments_deleted_by");

                    b.HasIndex("VisitId")
                        .HasDatabaseName("ix_medshack_treatments_visit_id");

                    b.ToTable("medshack_treatments", null, t =>
                        {
                            t.HasCheckConstraint("CK_MedshackTreatment_DeletedAtDeletedBy", "(deleted_at IS NULL) = (deleted_by IS NULL)");
                        });
                });

            modelBuilder.Entity("JffEhr.Api.Entities.MedshackVisit", b =>
                {
                    b.Property<Guid>("VisitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("visit_id");

                    b.Property<string>("AccompaniedBy")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("accompanied_by");

                    b.Property<string>("AdviceGiven")
                        .HasColumnType("text")
                        .HasColumnName("advice_given");

                    b.Property<string>("BloodPressure")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("blood_pressure");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<Guid?>("DoctorId")
                        .HasColumnType("uuid")
                        .HasColumnName("doctor_id");

                    b.Property<string>("Findings")
                        .HasColumnType("text")
                        .HasColumnName("findings");

                    b.Property<string>("MedicalHistory")
                        .HasColumnType("text")
                        .HasColumnName("medical_history");

                    b.Property<Guid>("NurseId")
                        .HasColumnType("uuid")
                        .HasColumnName("nurse_id");

                    b.Property<string>("NursingReport")
                        .HasColumnType("text")
                        .HasColumnName("nursing_report");

                    b.Property<int?>("OxygenSaturation")
                        .HasColumnType("integer")
                        .HasColumnName("oxygen_saturation");

                    b.Property<int?>("Pulse")
                        .HasColumnType("integer")
                        .HasColumnName("pulse");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<Guid>("RegistrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("registration_id");

                    b.Property<string>("SignsSymptoms")
                        .HasColumnType("text")
                        .HasColumnName("signs_symptoms");

                    b.Property<decimal?>("Temperature")
                        .HasColumnType("decimal(4,1)")
                        .HasColumnName("temperature");

                    b.Property<DateTimeOffset>("VisitAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("visit_at");

                    b.HasKey("VisitId")
                        .HasName("pk_medshack_visits");

                    b.HasIndex("DeletedBy")
                        .HasDatabaseName("ix_medshack_visits_deleted_by");

                    b.HasIndex("DoctorId")
                        .HasDatabaseName("ix_medshack_visits_doctor_id");

                    b.HasIndex("NurseId")
                        .HasDatabaseName("ix_medshack_visits_nurse_id");

                    b.HasIndex("RegistrationId")
                        .HasDatabaseName("ix_medshack_visits_registration_id");

                    b.ToTable("medshack_visits", null, t =>
                        {
                            t.HasCheckConstraint("CK_MedshackVisit_DeletedAtDeletedBy", "(deleted_at IS NULL) = (deleted_by IS NULL)");
                        });
                });

            modelBuilder.Entity("JffEhr.Api.Entities.Prescription", b =>
                {
                    b.Property<Guid>("PrescriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("prescription_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("deleted_by");

                    b.Property<string>("Dose")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("dose");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("frequency");

                    b.Property<string>("MedicationName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("medication_name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid?>("PrescribedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("prescribed_by");

                    b.Property<Guid>("RegistrationId")
                        .HasColumnType("uuid")
                        .HasColumnName("registration_id");

                    b.Property<string>("Route")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("route");

                    b.Property<string>("ScheduledTimes")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("scheduled_times");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("PrescriptionId")
                        .HasName("pk_prescriptions");

                    b.HasIndex("DeletedBy")
                        .HasDatabaseName("ix_prescriptions_deleted_by");

                    b.HasIndex("PrescribedBy")
                        .HasDatabaseName("ix_prescriptions_prescribed_by");

                    b.HasIndex("RegistrationId")
                        .HasDatabaseName("ix_prescriptions_registration_id");

                    b.ToTable("prescriptions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Prescription_DeletedAtDeletedBy", "(deleted_at IS NULL) = (deleted_by IS NULL)");
                        });
                });

            modelBuilder.Entity("JffEhr.Api.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CrewId")
                        .HasColumnType("uuid")
                        .HasColumnName("crew_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("RolePermissions")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("role_permissions");

                    b.HasKey("UserId")
                        .HasName("pk_users");

                    b.HasIndex("CrewId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_crew_id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("JffEhr.Api.Entities.AuditLog", b =>
                {
                    b.HasOne("JffEhr.Api.Entities.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_audit_logs_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JffEhr.Api.Entities.CampRegistration", b =>
                {
                    b.HasOne("JffEhr.Api.Entities.Camp", "Camp")
                        .WithMany("Registrations")
                        .HasForeignKey("CampId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_camp_registrations_camps_camp_id");

                    b.HasOne("JffEhr.Api.Entities.Camper", "Camper")
                        .WithMany("Registrations")
                        .HasForeignKey("CamperId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_camp_registrations_campers_camper_id");

                    b.Navigation("Camp");

                    b.Navigation("Camper");
                });

            modelBuilder.Entity("JffEhr.Api.Entities.CamperAssessment", b =>
                {
                    b.HasOne("JffEhr.Api.Entities.CrewMember", "AssessedByCrewMember")
                        .WithMany("AssessmentsPerformed")
                        .HasForeignKey("AssessedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_camper_assessments_crew_members_assessed_by");

                    b.HasOne("JffEhr.Api.Entities.CrewMember", "DeletedByCrewMember")
                        .WithMany()
                        .HasForeignKey("DeletedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_camper_assessments_crew_members_deleted_by");

                    b.HasOne("JffEhr.Api.Entities.CampRegistration", "Registration")
                        .WithOne("Assessment")
                        .HasForeignKey("JffEhr.Api.Entities.CamperAssessment", "RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_camper_assessments_camp_registrations_registration_id");

                    b.Navigation("AssessedByCrewMember");

                    b.Navigation("DeletedByCrewMember");

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("JffEhr.Api.Entities.Caregiver", b =>
                {
                    b.HasOne("JffEhr.Api.Entities.Camper", "Camper")
                        .WithMany("Caregivers")
                        .HasForeignKey("CamperId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_caregivers_campers_camper_id");

                    b.Navigation("Camper");
                });

            modelBuilder.Entity("JffEhr.Api.Entities.ConsentRecord", b =>
                {
                    b.HasOne("JffEhr.Api.Entities.CrewMember", "DeletedByCrewMember")
                        .WithMany()
                        .HasForeignKey("DeletedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_consent_records_crew_members_deleted_by");

                    b.HasOne("JffEhr.Api.Entities.CampRegistration", "Registration")
                        .WithMany("ConsentRecords")
                        .HasForeignKey("RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_consent_records_camp_registrations_registration_id");

                    b.Navigation("DeletedByCrewMember");

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("JffEhr.Api.Entities.CrewMedicalCheckin", b =>
                {
                    b.HasOne("JffEhr.Api.Entities.Camp", "Camp")
                        .WithMany("CrewMedicalCheckins")
                        .HasForeignKey("CampId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_crew_medical_checkins_camps_camp_id");

                    b.HasOne("JffEhr.Api.Entities.CrewMember", "CheckedInByCrewMember")
                        .WithMany("CheckInsPerformed")
                        .HasForeignKey("CheckedInBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_crew_medical_checkins_crew_members_checked_in_by");

                    b.HasOne("JffEhr.Api.Entities.CrewMember", "CrewMember")
                        .WithMany("MedicalCheckins")
                        .HasForeignKey("CrewId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_crew_medical_checkins_crew_members_crew_id");

                    b.Navigation("Camp");

                    b.Navigation("CheckedInByCrewMember");

                    b.Navigation("CrewMember");
                });

            modelBuilder.Entity("JffEhr.Api.Entities.EmergencyContact", b =>
                {
                    b.HasOne("JffEhr.Api.Entities.Camper", "Camper")
                        .WithMany("EmergencyContacts")
                        .HasForeignKey("CamperId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_emergency_contacts_campers_camper_id");

                    b.Navigation("Camper");
                });

            modelBuilder.Entity("JffEhr.Api.Entities.MedicationDose", b =>
                {
                    b.HasOne("JffEhr.Api.Entities.CrewMember", "AdministeredByCrewMember")
                        .WithMany("MedicationDosesAdministered")
                        .HasForeignKey("AdministeredBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_medication_doses_crew_members_administered_by");

                    b.HasOne("JffEhr.Api.Entities.CrewMember", "DeletedByCrewMember")
                        .WithMany()
                        .HasForeignKey("DeletedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_medication_doses_crew_members_deleted_by");

                    b.HasOne("JffEhr.Api.Entities.Prescription", "Prescription")
                        .WithMany("Doses")
                        .HasForeignKey("PrescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_medication_doses_prescriptions_prescription_id");

                    b.Navigation("AdministeredByCrewMember");

                    b.Navigation("DeletedByCrewMember");

                    b.Navigation("Prescription");
                });

            modelBuilder.Entity("JffEhr.Api.Entities.MedicationEvent", b =>
                {
                    b.HasOne("JffEhr.Api.Entities.CrewMember", "DeletedByCrewMember")
                        .WithMany()
                        .HasForeignKey("DeletedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_medication_events_crew_members_deleted_by");

                    b.HasOne("JffEhr.Api.Entities.CampRegistration", "Registration")
                        .WithMany("MedicationEvents")
                        .HasForeignKey("RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_medication_events_camp_registrations_registration_id");

                    b.HasOne("JffEhr.Api.Entities.CrewMember", "Reporter")
                        .WithMany("MedicationEventsReported")
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_medication_events_crew_members_reporter_id");

                    b.HasOne("JffEhr.Api.Entities.CrewMember", "Reviewer")
                        .WithMany("MedicationEventsReviewed")
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_medication_events_crew_members_reviewer_id");

                    b.Navigation("DeletedByCrewMember");

                    b.Navigation("Registration");

                    b.Navigation("Reporter");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("JffEhr.Api.Entities.MedshackTreatment", b =>
                {
                    b.HasOne("JffEhr.Api.Entities.CrewMember", "AdministeredByCrewMember")
                        .WithMany("MedshackTreatmentsAdministered")
                        .HasForeignKey("AdministeredBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_medshack_treatments_crew_members_administered_by");

                    b.HasOne("JffEhr.Api.Entities.CrewMember", "DeletedByCrewMember")
                        .WithMany()
                        .HasForeignKey("DeletedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_medshack_treatments_crew_members_deleted_by");

                    b.HasOne("JffEhr.Api.Entities.MedshackVisit", "Visit")
                        .WithMany("Treatments")
                        .HasForeignKey("VisitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_medshack_treatments_medshack_visits_visit_id");

                    b.Navigation("AdministeredByCrewMember");

                    b.Navigation("DeletedByCrewMember");

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("JffEhr.Api.Entities.MedshackVisit", b =>
                {
                    b.HasOne("JffEhr.Api.Entities.CrewMember", "DeletedByCrewMember")
                        .WithMany()
                        .HasForeignKey("DeletedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_medshack_visits_crew_members_deleted_by");

                    b.HasOne("JffEhr.Api.Entities.CrewMember", "Doctor")
                        .WithMany("MedshackVisitsAsDoctor")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_medshack_visits_crew_members_doctor_id");

                    b.HasOne("JffEhr.Api.Entities.CrewMember", "Nurse")
                        .WithMany("MedshackVisitsAsNurse")
                        .HasForeignKey("NurseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_medshack_visits_crew_members_nurse_id");

                    b.HasOne("JffEhr.Api.Entities.CampRegistration", "Registration")
                        .WithMany("MedshackVisits")
                        .HasForeignKey("RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_medshack_visits_camp_registrations_registration_id");

                    b.Navigation("DeletedByCrewMember");

                    b.Navigation("Doctor");

                    b.Navigation("Nurse");

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("JffEhr.Api.Entities.Prescription", b =>
                {
                    b.HasOne("JffEhr.Api.Entities.CrewMember", "DeletedByCrewMember")
                        .WithMany()
                        .HasForeignKey("DeletedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_prescriptions_crew_members_deleted_by");

                    b.HasOne("JffEhr.Api.Entities.CrewMember", "PrescribedByCrewMember")
                        .WithMany("PrescriptionsPrescribed")
                        .HasForeignKey("PrescribedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_prescriptions_crew_members_prescribed_by");

                    b.HasOne("JffEhr.Api.Entities.CampRegistration", "Registration")
                        .WithMany("Prescriptions")
                        .HasForeignKey("RegistrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_prescriptions_camp_registrations_registration_id");

                    b.Navigation("DeletedByCrewMember");

                    b.Navigation("PrescribedByCrewMember");

                    b.Navigation("Registration");
                });

            modelBuilder.Entity("JffEhr.Api.Entities.User", b =>
                {
                    b.HasOne("JffEhr.Api.Entities.CrewMember", "CrewMember")
                        .WithOne("User")
                        .HasForeignKey("JffEhr.Api.Entities.User", "CrewId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_users_crew_members_crew_id");

                    b.Navigation("CrewMember");
                });

            modelBuilder.Entity("JffEhr.Api.Entities.Camp", b =>
                {
                    b.Navigation("CrewMedicalCheckins");

                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("JffEhr.Api.Entities.CampRegistration", b =>
                {
                    b.Navigation("Assessment");

                    b.Navigation("ConsentRecords");

                    b.Navigation("MedicationEvents");

                    b.Navigation("MedshackVisits");

                    b.Navigation("Prescriptions");
                });

            modelBuilder.Entity("JffEhr.Api.Entities.Camper", b =>
                {
                    b.Navigation("Caregivers");

                    b.Navigation("EmergencyContacts");

                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("JffEhr.Api.Entities.CrewMember", b =>
                {
                    b.Navigation("AssessmentsPerformed");

                    b.Navigation("CheckInsPerformed");

                    b.Navigation("MedicalCheckins");

                    b.Navigation("MedicationDosesAdministered");

                    b.Navigation("MedicationEventsReported");

                    b.Navigation("MedicationEventsReviewed");

                    b.Navigation("MedshackTreatmentsAdministered");

                    b.Navigation("MedshackVisitsAsDoctor");

                    b.Navigation("MedshackVisitsAsNurse");

                    b.Navigation("PrescriptionsPrescribed");

                    b.Navigation("User");
                });

            modelBuilder.Entity("JffEhr.Api.Entities.MedshackVisit", b =>
                {
                    b.Navigation("Treatments");
                });

            modelBuilder.Entity("JffEhr.Api.Entities.Prescription", b =>
                {
                    b.Navigation("Doses");
                });

            modelBuilder.Entity("JffEhr.Api.Entities.User", b =>
                {
                    b.Navigation("AuditLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
